### ISSUE TITLE
Not Loading any audio file

### ISSUE THREAD

**Issue by xankent** [morevnaproject/papagayo-ng#126]
I have try to load .wav, .mp3 in different qualityts on the new NG1.7 the one with the AI and Download buttons, but it seems not working. The green bar blinks a little and then nothing.
![imagen](https://github.com/morevnaproject-org/papagayo-ng/assets/115520314/baf57dc9-2198-474c-8863-581c4d694b47)
![imagen](https://github.com/morevnaproject-org/papagayo-ng/assets/115520314/ab5bc12e-7d14-4310-9f3c-764f6cecfad7)

**Comment by steveway** [comment]
Hi,
Did you download FFMPEG?
In the top menu there is a Download menu, one of the options allows you to
download or Update FFMPEG.
After that is finished you need to close and open Papagayo-NG again.
Also in the AppData folder, which can be opened through the settings and
there under Misc, there should be 2 log files.
If it still doesn't work after getting FFMPEG then send me the log files
from that folder, I will take a look to see what might be the problem.

**Comment by xankent** [comment]
thans for answering, the log file its empty

[image: imagen.png]

**Comment by xankent** [comment]
I have done the following

1. Reload all the software on the Reload section
2. Change the language

now its loading the audio, seems to be working but!! now when I press play
the mouth says following

[image: imagen.png]

**Comment by steveway** [comment]
Hello, your last image didn't transfer.
But I have a suspicion of what might be the problem, so I will copy what I wrote to a similar sounding problem:

> I see, that is because the default mouth you have currently selected for the preview is made for Preston Blair Phonemes.
But the detection from Allosaurus outputs CMU Phonemes.
So to get a correct Playback you can select one of the 2 last mouths in the dropdown for the preview.
You can also convert it to a different set, you might want to do this so you have less different shapes for the output.
To do that, select the phoneme set you want from the dropdown on the bottom, next to the language.
Then on the top click on Conversion and there on Convert Phonemes.
It will then convert the phonemes to the selected set.

**Comment by xankent** [comment]
y just re install all in fresh, maybe Im doing something wrong

1. How can I "split" the text like in the old softares? withou using the
"voice recog"?

2. because wen using the autodetection dosent allow me to stretch
3. Im worgin in spanish, trying to use this as the previous version, but
the previouse version dosent allow me to scrubb the audio, so we decide to
try this one .

Can you help me please?

[image: imagen.png]

**Comment by steveway** [comment]
1. Simply type in the text manually in the "Spoken Text" input. After that click on "Breakdown", make sure that language and phoneme set are set to the left of the button.
2. What do you mean with stretch? I'm not sure I understand.
3. Scrubbing should work with this version.
Your pictures are not being sent correctly, I guess Github removes them for some reason.

**Comment by AlexHemza** [comment]
Checked on two computers—doesn’t work anywhere. Won’t open settings, and no files are accessible. Even though I installed it normally and downloaded everything. 

![Image](https://github.com/user-attachments/assets/8a69ee04-8604-4c02-9c6a-782551370941)

**Comment by steveway** [comment]
Hi, can you tell me which version you are using and on what system you are using this.

**Comment by AlexHemza** [comment]
Windows 10 Pro. 17, 18 versions. I took them from steveway.gumroad, and if anything, Windows Defender complained about malicious files during installation

**Comment by steveway** [comment]
Mhh, that is strange, I can't reproduce it.
If you can test, the code directly from this repo, does it also not work?
https://github.com/steveway/papagayo-ng

**Comment by AlexHemza** [comment]
I am not a programmer or a tester, I downloaded the installation files both msi and exe, tried again - the program does not work, does not open files and does nothing

**Comment by steveway** [comment]
I see, I am preparing another update with some more fixes. Can you copy the runtime.log file from the settings folder of your papagayo? After trying to open a file and then closing Papagayo. You can reach it easily via the settings menu.

**Comment by AlexHemza** [comment]
runtime.log in AppData\Local\Morevna Project\PapagayoNG empty

**Comment by steveway** [comment]
Oh, that is very unusual.
Normally it should output any tracebacks or exceptions there.
If you got this via Gumroad then you should be able to download a new update V1.9.0.0 from there now.
Maybe this helps with your problems.

**Comment by AlexHemza** [comment]
I managed to open an audio file, which for some reason takes about two minutes to open. Although I have a fast computer. However, I can't get any further - I make settings and press Breakdown and... nothing happens.
Log:
2025-04-29 09:19:53,459:predict:661:Error running Allosaurus: unknown format: 3
2025-04-29 09:19:53,460:predict:662:Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\recognizer.py", line 561, in predict
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\allosaurus\app.py", line 71, in recognize
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\allosaurus\audio.py", line 17, in read_audio
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 649, in open
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 286, in __init__
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 266, in initfp
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 383, in _read_fmt_chunk
wave.Error: unknown format: 3

2025-04-29 09:48:50,299:predict:661:Error running Allosaurus: unknown format: 3
2025-04-29 09:48:50,299:predict:662:Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\recognizer.py", line 561, in predict
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\allosaurus\app.py", line 71, in recognize
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\allosaurus\audio.py", line 17, in read_audio
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 649, in open
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 286, in __init__
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 266, in initfp
  File "C:\Users\Alex\AppData\Local\Temp\ON1135~1\wave.py", line 383, in _read_fmt_chunk
wave.Error: unknown format: 3

2025-04-29 21:29:04,614:predict:661:Error running Allosaurus: unknown format: 3
2025-04-29 21:29:04,615:predict:662:Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\recognizer.py", line 561, in predict
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\allosaurus\app.py", line 71, in recognize
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\allosaurus\audio.py", line 17, in read_audio
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\wave.py", line 649, in open
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\wave.py", line 286, in __init__
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\wave.py", line 266, in initfp
  File "C:\Users\Alex\AppData\Local\Temp\ON70AD~1\wave.py", line 383, in _read_fmt_chunk
wave.Error: unknown format: 3

**Comment by steveway** [comment]
I see, it might be some incompatibility with your audio files.
Do you have some files you can share which produce this problem?

Here you can find some audio files which we are using for testing:
https://github.com/LostMoho/Papagayo/tree/master/installer/Papagayo/Tutorial%20Files
