### ISSUE TITLE
Port to QT

### ISSUE THREAD

**Issue by steveway** [morevnaproject/papagayo-ng#33]
So, since I've made some nice progress in my branch, I thought I'd open this "Issue" here to get some exposure on this.
https://github.com/steveway/papagayo-ng/tree/papagayo-ng-qt
So, what do I have planned with this?
First I obviously want to port Papagayo-ng to QT because this should allow us to more easily fix our performance issues.
Next while I'm converting everything manually, I'm also fixing the CamelCase mess with the better snake_case.
We can also now change the design/layout more easily by only changing the ui file, either by hand or using QT-Designer.
And of course the short term end goal is feature parity with the current WX version.

What does currently work?
Not a lot, but it's starting to get interesting now.
We can open the program, which shows a familiar window, we can also open a sound file or a papagayo project file.
(Actually I just tested and Project files are broken at the moment.)
The background grid and the Waveform get drawn.
The About Box is working and the Help Topics Button opens the Github currently.
Text can be entered most places.
Config settings are saved and recalled using QTs config options.
The Comboboxes and Listviews get populated and the Mouthview currently shows the default mouth.

There might also be more things that currently work and more that don't.

Feel free to take a look at it (use papagayo-ng-qt-direct.py)  and maybe fix/add more functionality to it.
If there are comments or questions I'll try to answer them here.

**Comment by morevnaproject** [comment]
Woah, what a great initiative! I am both hands for moving in this direction. Of course, we will need to completely re-write our packaging scripts, but @blackwarthog will handle this as soon as that will be ready. Thank you very much for such effort!

**Comment by morevnaproject** [comment]
Tested on Ubuntu 16.04.

First, I have tried to run, but got the following error:
```
$ python3 papagayo-ng-qtdirect.py 
Traceback (most recent call last):
  File "papagayo-ng-qtdirect.py", line 4, in <module>
    import LipsyncFrameQT
  File "/home/konstantin/sources/papagayo/LipsyncFrameQT.py", line 35, in <module>
    from WaveformViewQT import WaveformView
  File "/home/konstantin/sources/papagayo/WaveformViewQT.py", line 27, in <module>
    import simplestopwatch as stopwatch
ImportError: No module named 'simplestopwatch'
```

So I did this command:
```$ pip3 install simplestopwatch```

After that it is started well -
![screenshot_005](https://user-images.githubusercontent.com/332868/30147821-89afdfa4-93ca-11e7-8a9a-aa69ddd0ecb3.png)

Looks good so far!

**Comment by morevnaproject** [comment]
I have created a separate GitHub Project Board to collect issues related with QT port - https://github.com/morevnaproject/papagayo-ng/projects/2

**Comment by steveway** [comment]
Oh right, I used the simplestopwatch also in my last improvements to do some simple timing, maybe wrapping it in a try-except makes more sense since it is not really critical and I'm already putting it in a conditional block checking for it's existence.
The UI looks pretty nice on your Ubuntu!
The only real new dependency should be PySide, which I mostly chose because the license is more lenient, but it also seems to now be the preferred Python bindings for QT now:
https://groups.google.com/d/msg/pyside-dev/pqwzngAGLWE/kXUpXBhILAAJ

My first idea was porting this to use Kivy, since it would allow us to get this to run more easily on mobile platforms.
But the jump would have been too big compared to porting to Qt.
Also this is not using QtQuick/QML mostly for the same reason.

Next I'll fix the loading of project files, I kinda know what the problem is, and then I'd like to try rendering the sentences/words/phonemes in the Waveformview from that.
Then we'll have a real rough first step and can start to get everything to run together.

**Comment by steveway** [comment]
Loading of Project files is now working.
I also moved the rendering of the background lines and numbers to a separate function which draws this on a separate layer.
I'm thinking of also moving the play marker to the foreground layer the same way.
Actually, maybe moving the Waveform to the background layer would make sense, not sure if we will gain anything performance-wise.
It should be not too complicated to test this later when we are drawing everything.
Would be cool if someone wants to take a look why the quick resizing inside the on_resize of LipsyncFrameQT is behaving buggy.
The real resizing, done by do_idle seems to be working correctly, but the quick preview one is behaving a bit incorrect.
But don't invest too much work or time into that yet until all rendering is implemented, since that work might not be used in the end.

**Comment by steveway** [comment]
Had done some testing on the rendering of the Phonemes, Words and Sentences in the last few commits.
Also in the current commit b1841354a63136328eb9841624f34717a35c1010 , I changed the project from using PySide directly to using [qtpy](https://github.com/spyder-ide/qtpy).
The reason for qtpy instead of [Qt.py](https://github.com/mottosso/Qt.py) is that qtpy handles custom widgets better, didn't get it to work with Qt.py.
As I mentioned in the commit, I tested this using PyQt5 and PySide.
I also tested PySide2 from Anaconda on Windows, but the Anaconda people removed all the WebView stuff from their release, afaik because they don't support C++11 or something like that...

**Comment by steveway** [comment]
I just saw that a parrot/papagayo is called a perroquet in French.
So, rebranding this Port as perroQueT or a similar spelling would be an option.
Not too important, but an interesting thing to keep in mind.

**Comment by steveway** [comment]
The QT branch now renders the Sentences, Words and Phonemes!
You can drag and drop them but that currently doesn't change anything behind the scenes.
Also they are all in the same color-scheme, but that's easy to change.
It's nice seeing the backend cooperating when you implement frontend stuff.
Since almost everything is available visually it is time to implement more functionality.
If anyone wants to join here is a list of  a few "easy" things that still need to be re-implemented:
- drawing the play-marker
- connect the play-pause buttons to their functions
- change the selected mouth with the drop-down
- change the selected voice using the voice-list (might be a bit more complicated)
- fix the zoom buttons
- test/fix saving
- implement dragging restrictions
- make dragging and resizing change the actual values
- connect volume slider
- adding and deleting a new voice
- export buttons

Resizing is still slightly buggy, the phonemes currently disappear sometimes for example.
Alright, if someone wants to jump in, please first tell us what you'd like to do so we can avoid duplicate work.

**Comment by steveway** [comment]
Please look at my previous comment for some status update.

**Comment by morevnaproject** [comment]
Hello @steveway! Awesome work, I am taking this for testing.

Quick news from my side: I have found a person, who is willing to integrate Rhubarb lipsync into Papagayo - #44. We plan to integrate into QT port, so you finished it just in time. Will take some time for testing and get back to you with feedback. Thank you!

**Comment by morevnaproject** [comment]
Okay, I have installed Pyside2 to my Ubuntu 16.04 (https://askubuntu.com/questions/826437/how-to-install-pyside2-uic-in-ubuntu-16-04) and launched:
```
$ python3 papagayo-ng-qtdirect.py 
Traceback (most recent call last):
  File "papagayo-ng-qtdirect.py", line 4, in <module>
    import LipsyncFrameQT
  File "/home/konstantin/sources/papagayo/LipsyncFrameQT.py", line 35, in <module>
    from WaveformViewQT import WaveformView
  File "/home/konstantin/sources/papagayo/WaveformViewQT.py", line 29, in <module>
    from LipsyncDoc import *
  File "/home/konstantin/sources/papagayo/LipsyncDoc.py", line 32, in <module>
    import SoundPlayer
  File "/home/konstantin/sources/papagayo/SoundPlayer.py", line 7, in <module>
    import sounddevice as sd
ImportError: No module named 'sounddevice'
```

So, I have installed sounddevice python module:
```
$ python3 papagayo-ng-qtdirect.py 
```

Then it started well.

I tried to open a file and git the following error:

```
self.path: /home/konstantin/0-work/morevna/ep03/004/004-90-en.pgo
self.soundDuration: 76
Traceback (most recent call last):
  File "/home/konstantin/sources/papagayo/LipsyncFrameQT.py", line 210, in on_open
    self.open(file_path)
  File "/home/konstantin/sources/papagayo/LipsyncFrameQT.py", line 216, in open
    self.doc.open(path)
  File "/home/konstantin/sources/papagayo/LipsyncDoc.py", line 505, in open
    self.open_audio(self.soundPath)
  File "/home/konstantin/sources/papagayo/LipsyncDoc.py", line 515, in open_audio
    self.sound = SoundPlayer.SoundPlayer(self.soundPath, self.parent)
  File "/home/konstantin/sources/papagayo/SoundPlayer.py", line 59, in __init__
    self.audio.default.samplerate = self.pydubfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
```

Here is the file - [004-90-en.pgo.zip](https://github.com/morevnaproject/papagayo-ng/files/2331555/004-90-en.pgo.zip)

**Comment by morevnaproject** [comment]
Okay, seems like I do not have pydub. Installed it and now it loads fiile successfully. 

Should we make some tweaks of ```SoundPlayer.py``` on line 50? (for the case when pydub isn't found).

**Comment by steveway** [comment]
Cool, I pushed a small change for line 59 which should fix that.

**Comment by steveway** [comment]
Yes, that is not yet perfect, it works mostly but needs improvements.
The resize handle is only on the right side, currently by design.
Maybe it would make sense to highlight that part in a darker shade maybe.
To get rid of the jumping we should move/resize the children of the elements we touched so that they stay in their constraints.
And some of the jumping is possibly because of the changed rounding in newer Python 3 version, we should check all places where coordinates get rounded and converted.
I also just saw that you can resize phonemes, I'm pretty sure that is not what we actually want.

**Comment by morevnaproject** [comment]
> The resize handle is only on the right side, currently by design.

I like that.

> Maybe it would make sense to highlight that part in a darker shade maybe.

That's good idea!

> I also just saw that you can resize phonemes, I'm pretty sure that is not what we actually want.

Absolutely agree. ^__^

**Comment by steveway** [comment]
Alright, I added a marker, rendering these few pixels correctly is for some reason difficult for QT...
And Phonemes can't be resized anymore.

**Comment by morevnaproject** [comment]
Great! I have tested the latest changes and with resize markers it is much easier to understand now.

> To get rid of the jumping we should move/resize the children of the elements we touched so that they stay in their constraints.

Yes, resizing child elements is necessary function. Will you be able to implement that? ^__^

**Comment by morevnaproject** [comment]
Hello @steveway! Any news on that topic? ^__^

**Comment by steveway** [comment]
A little bit. I've tried to locate the cause of the problem.
I don't really understand the cause, but I've created a fix/workaround which seems to be stable.
So, editing phonemes seems to work now.
I've also added a bit of code that repositions child elements when resizing phrases or words.

**Comment by morevnaproject** [comment]
Hi! Thank you for the update! I have tested latest changes - resizing of words works better now, but still some glitches happen from time to time (sometimes it refuses to expand, even if there is enough room for that). Moving words or phonemes still have same issues - it is jumping to arbitrary place (as shown in the video fo this https://github.com/morevnaproject/papagayo-ng/issues/33#issuecomment-416917621).  Reposition of child elements works good so far! ^__^

**Comment by morevnaproject** [comment]
Hello @steveway! I have tested latest changes. I think it's better now - resizing seems to work perfectly!
Moving any element is problematic - the element is jumping to left as soon as I start dragging it.
Here's how it works for me now - https://youtu.be/WbfWWbeY_U4

**Comment by morevnaproject** [comment]
Hello! I have tested latest commit - 69c243cda4 - and (unfortunately) the effect seems to be the same.
Here is a video - https://youtu.be/3Kg-FKp-YK8

In the meantime I am investigating how we can use RhubarbLipSync (#44) for automatic phoneme alignment. And first results are quite promising! I think, we will be able to integrate it with Papagayo.

Thank you for your efforts!

**Comment by morevnaproject** [comment]
Quick update: @evgenijkatunov has made first steps on integrating Rhubarb into Papagayo-NG - https://github.com/evgenijkatunov/papagayo-ng/tree/papagayo-ng-qt-rhubarb

When user opens file it automatically parsed through Rhubarb and phonemes are auto-detected.

To operate succesfully it requires Rhubarb binary available at "./rhubarb/rhubarb" path.

**Comment by morevnaproject** [comment]
@steveway BTW, I have weird issues with sound playback - it plays at the very low pitch. Can you please let me know what sound engine you use - sounddevice or pydub?

**Comment by morevnaproject** [comment]
Considering the current direction of development, I an going to merge QT and Rhubarb into "master" branch in nearest time. For anyone who would like to fix old 1.4.2 version (current state of master branch) we will create separate branch called "1.4.x". This will help to avoid situation when people start contributing to an outdated WXWidgets-based code. I think this also can speedup development of QT-based version, as we can attract more contributors here.

**Comment by morevnaproject** [comment]
Okay, QT version is in  "master" now. 

Old Wx-based version in 1.4.2 branch (https://github.com/morevnaproject/papagayo-ng/tree/1.4.x).

**Comment by morevnaproject** [comment]
We've got Rhubarb feature merged just now. - #50 ^__^

**Comment by steveway** [comment]
Cool, I've changed my master to that one too.
I've done some tests with the audio slow-down bug.
It seems to not happen on all files, I've tested the old Tutorial File, lame.pgo, and there it runs normally.
But my own project file is slowed down.
Currently we load the file with pydub, get some information about it from there, throw that to sounddevice and tell it to play it.
We should likely try to change that to the audio functionality that PySide2 offers, so something from here:
https://doc.qt.io/qtforpython/PySide2/QtMultimedia/QAudioOutput.html
Mhh, searching in the docs this seems to be a easy way to get something usable:
https://doc.qt.io/qtforpython/PySide2/QtMultimedia/QMediaPlayer.html
If that works we might be able to remove pydub and sounddevice from our dependencies.

**Comment by morevnaproject** [comment]
@steveway Cool! Just a quick note from my experience: utilizing QMediaPlayer allowed us to get a good sound support in OpenToonz for Linux and OSX platforms. ^__^

**Comment by morevnaproject** [comment]
> It seems to not happen on all files, I've tested the old Tutorial File, lame.pgo, and there it runs normally.

Thank you for the note! I also tested on the same file (https://github.com/LostMoho/Papagayo/raw/master/installer/Papagayo/Tutorial%20Files/lame.wav) and it also works fine for me.

**Comment by steveway** [comment]
Alright, regarding rewriting the WaveformView, I've taken a look at it and wrote down some thoughts.
These mostly relate to the "MovableButton" class:

- We need the parent element if it exists, and the previous and next element if they exist
- When we move we need to check for the boundaries dictated by the parent and neighbors.
- Inform our neighbors after we finished moving, should be automatic if references are used for that.
- Getting new neighbors or loosing some is problematic.
- Maybe a structure with all elements makes sense, it's a bit circular but should work.
- It should somehow represent the actual data so that we can find our neighbors...
- So the mov_widget_list should maybe be a list of lists instead
- But to find our position in that we would have to parse through the whole list then...

Does anyone have a good idea for a datastructure that we can use that keeps everything organized but allows one to find a specific item and it's surrounding neighbors, parent and children if applicable?
Maybe something like a linked-list, but do these handle hierarchies with parents, children and neighbors?

**Comment by steveway** [comment]
I've done some tests with the anytree package, but that still gives me some problems.
Here is my testcode, it's a bit unsorted:
```
#!/usr/bin/env python

from anytree import Node, RenderTree
import anytree.util
import anytree.search


class MovableButton():
	def __init__(self, title, tree):
		self.title = title
		self.tree  = tree
		#self.tree_node = tree.values
		print(type(self))
		print(self)
		print(tree)
		# This find returns None !
		self.node = anytree.search.find(self.tree, lambda node: node.name == self)
		print(self.node)
	def get_title(self):
		return self.title
		
	def get_left_sibling(self):	
		return anytree.util.leftsibling(self.node)
		
		
	
		
alltext = Node("everything")
firstphrase = Node(MovableButton("firstphrase1",alltext),parent=alltext)
firstword = Node(MovableButton("firstword1",alltext),parent=firstphrase)
secondword = Node(MovableButton("secondword2",alltext),parent=firstphrase)
thirdword = Node(MovableButton("thirdword1",alltext),parent=firstphrase)

secondphrase = Node(MovableButton("secondphrase2",alltext),parent=alltext)

thirdphrase = Node(MovableButton("thirdphrase3",alltext),parent=alltext)

for pre, fill, node in RenderTree(alltext):
	print("%s%s" % (pre, node.name))
		
for pre, fill, node in RenderTree(alltext):
	try:
		print("Node: ")
		print(node.name.node)
		print("Name: ")
		print(node.name.get_title())
		print("LeftSibling: ")
		print(node.name.get_left_sibling())
	except AttributeError:
		pass
print(type(secondword.name))		
# This find works...
print(anytree.search.find(alltext, lambda node: node.name == secondword.name))
for pre, fill, node in RenderTree(thirdphrase.name.tree):
	print("%s%s" % (pre, node.name))
```
The problem is that the Buttons Objects can't find themselves in the tree.
We could manually add the Node to the Movable Button after both have been created

Actually, I've just tested this and that does seem to work:
```
#!/usr/bin/env python

from anytree import Node, RenderTree
import anytree.util
import anytree.search


class MovableButton():
	def __init__(self, title, tree):
		self.title = title
		self.tree  = tree
		#self.tree_node = tree.values
		self.node = None
	def get_title(self):
		return self.title
		
	def get_left_sibling(self):	
		return anytree.util.leftsibling(self.node)
		
	def add_node(self, node):
		self.node = node
		
		
temp_button = None
temp_parent_phrase = None
temp_parent_word = None
node_list = []
		
alltext = Node("everything")
temp_button = MovableButton("firstphrase1",alltext)
temp_button.node = Node(temp_button,parent=alltext)
node_list.append(temp_button.node) # So it doesn't get gc'd
temp_parent_phrase = temp_button.node # keep the parents in mind when we move to the children
temp_button = MovableButton("firstword1",alltext)
temp_button.node = Node(temp_button,parent=temp_parent_phrase)
node_list.append(temp_button.node) # So it doesn't get gc'd

temp_button = MovableButton("secondword2",alltext)
temp_button.node = Node(temp_button,parent=temp_parent_phrase)
node_list.append(temp_button.node) # So it doesn't get gc'd

temp_button = MovableButton("thirdword1",alltext)
temp_button.node = Node(temp_button,parent=temp_parent_phrase)
node_list.append(temp_button.node) # So it doesn't get gc'd

temp_button = MovableButton("secondphrase2",alltext)
temp_button.node = Node(temp_button,parent=alltext)
node_list.append(temp_button.node) # So it doesn't get gc'd

temp_button = MovableButton("thirdphrase3",alltext)
temp_button.node = Node(temp_button,parent=alltext)
node_list.append(temp_button.node) # So it doesn't get gc'd


for pre, fill, node in RenderTree(alltext):
	print("%s%s" % (pre, node.name))
		
for pre, fill, node in RenderTree(alltext):
	try:
		print("Node: ")
		print(node.name.node) # We could just use node but I want to see if the variable in the class is correct
		print("Name: ")
		print(node.name.get_title())
		print("LeftSibling: ")
		print(node.name.get_left_sibling().name.title)
		print("Parent: ")
		print(node.name.node.parent)
	except AttributeError:
		pass
```
So here we have a tree and every element should be able to find it's parent and neighbors.
Some more testing with removing and adding is needed but this seems like a viable solution.

**Comment by steveway** [comment]
Alright, I've now started integrating this step by step.
https://github.com/steveway/papagayo-ng/commit/fc12448373af2597dc678f978001e3ae1b4ab0d1
The Waveform and Background and Buttons are already being rendered correctly.
Resizing the window is fast and looks correct.
Actually, if we resize the Waveform Polygon instead of redrawing this might be even faster.
Zooming works for the Buttons and Background but not the Waveform, dunno why.
I copy-pasted the zooming from the old one, but it only gives problems for the Waveform.

If you click on a Button it'll try to tell you what it's left and right sibling is, and it will tell you the left_most and right_most frame position it can move to/resize into.
It does get these coordinates from the Lipsync objects themselves and uses the nodes to find the correct object to the left, right or if not applicable it looks at it's parent.

This Treestructure should help eliminate the annoying bugs we had when creating and deleting parts, especially phonemes.
If we use the dialog to set new phonemes for a word we can now apply these somehow like this:
- we can easily get the children of the currently selected word using the nodes and delete them from the scene, the mov_widget_list and themselves completely
- after that we can create new children for this word, insert them into the scene and the mov_widget_list
- then everything should work as expected, the place in the mov_widget_list and scene shouldn't matter

Another bug I'm not sure about is the scrollbar, it doesn't seem to show the scrollhandle yet.
And of course most functions aren't yet implemented like all interaction with Buttons.
Also the Playmarker is not yet implemented.

I think this could be a good basis for a more structured WaveFormView, let's see how long it'll take me to finish this.

@morevnaproject

**Comment by morevnaproject** [comment]
That's awesome!

**Comment by steveway** [comment]
Alright, some more improvements.
I removed the mov_widget_list, we should be able to use the nodes instead.
The zoom is mostly fixed, there is still a refresh problem, and it changes the scene width too much.
So it's a bit cleaner and more stable, I'll try to fix everything first before implementing more functionality.

**Comment by steveway** [comment]
My newest commit finished zooming and resizing pretty much.
There is still a small bug when zooming, it doesn't redraw everything sometimes, but that's not too bad.
I've tested throwing some update() calls around but couldn't fix that yet, maybe someone else has an idea.

**Comment by morevnaproject** [comment]
Hi! My apologies, I am in hurry for preparing the release of new Morevna Episode (which is coming on 05.05.2019), so I cannot be much help those days.  Many apologies for that! ^__^"

@evgenijkatunov @blackwarthog Can you look at the code please and give some feedback?

**Comment by steveway** [comment]
No problem.
I mostly use this issue to keep in mind what I've done already and what my next steps are.
Also to inform everyone interested about the updates in a slightly more understandable form.

**Comment by steveway** [comment]
Besides the artifacts, resizing and zooming is pretty much perfect now.
Just saw, there seems to be a small bug where the object resizes when moving it, likely a rounding error.
I also experimented with repositioning descendants when one moves or resizes a word or phrase.
The easiest way would likely be to iterate over the children then, shrink the child to it's minimal size and move it to either the right of its' left sibling or the left of it's parent.
And do the same for their children if they have any.
There are likely some smart algorithms we could use to best fit the descendants.

**Comment by steveway** [comment]
Ok, if I haven't forgotten anything the rewrite should have the same features as the old version.
And it should also have less bugs and stuff.

**Comment by steveway** [comment]
Alright, some more fixes to resizing and moving logic.
Also some refactoring, for example the widget now sets its' style itself on init.
There is one more bug in the resize/move logic as far as I can see:
When you resize to a widget to the minimum size or below then it switches from resizing to moving the widget.
That's only slightly annoying, could be worse.
I think I'll look back at the sound stuff again next, I'll try to get the QAudioBuffer stuff working with more different files using my cffi method.

**Comment by steveway** [comment]
Ok, I have fixed the loading of all sample files.
For whatever reason when the samples are 8bit then you need to subtract 128 from them...
Also Unicode wasn't handled correctly, fixed that too.
So I'd say we can replace the current QT Version of Papagayo-NG with my rewrite.
Some further re-testing and fixing under OSX is likely needed, but Linux and Windows should work.

**Comment by steveway** [comment]
And some more fixes.
I placed some processEvents() calls to fix some, possible all, artifacting.
And I added the play marker to playback via double click.
I believe that my fix for those 8bit samples needs to be done because they are unsigned and not necessarily because they are 8bit.
That at least makes a bit more logical sense and still works for the samples.

**Comment by steveway** [comment]
Alright more stuff done.
I changed the Sound stuff for OSX so it should use QT for playback and pydub or wave + audioop for decoding.
Also I implemented the AboutBox, it's a tiny bit of a workaround but seems to work.

**Comment by steveway** [comment]
Made some more changes and "improvements".

As a reminder for me:
- find out if the text fits into the button
- if not find out how much fits
- show the full text with a mousehover tooltip thingy
If we can do that it should help fix some rendering bugs.

**Comment by steveway** [comment]
Ok, I can't sleep and did that stuff. Changing the font size works but get's unreadable fast.
The scene size now get's calculated from the Background without using the Waveform Boundingrect.
And the Waveform is now being placed better vertically.

**Comment by steveway** [comment]
So after I added a lot of things and tested a lot, I thought that the recognition for changes is currently a bit annoying and likely incorrect.
So, the best method would be if the phonemes, words, phrases and voices from lipsyncdoc would recognize themselves that they have been changed.
We can add that without having to change too much code by using properties like this for example:
```python
class LipsyncPhoneme:
    def __init__(self):
        self.text = ""
        self._frame = 0
        self.dirty = False
        self.is_phoneme = True

        @property
        def frame(self):
            return self._frame

        @frame.setter
        def frame(self, value):
            if self._frame != value:
                self.dirty = True
                self._frame = value
```
We should then be able to set and get the value as before but a change is recognized and the Phoneme marks itself as dirty.
For some reason we are not using the __init__ method to fill the initial values, so we have to make sure to mark it as not dirty after the first creation.
Or we change the code to properly use the __init__ method, which likely will save some lines too.

**Comment by steveway** [comment]
Couldn't sleep, so I pretty much fixed resizing.
The bug where it changes from resizing to moving is fixed.
And I've implemented an algorithm which should fit the words perfectly into the phrases.
This also keeps in mind the minimum size of the words and spaces the phonemes as evenly possible.
Also, if you try to resize an object that is smaller than it's minimum size it will first set it to it's minimum size.
Also, I've thought a bit about the minimum size, I believe now that this makes the most sense.
Otherwise we would allow phonemes to possibly overlap, which would mean in an animation it would try to show two mouths at the same time.

**Comment by steveway** [comment]
Ok, I just fixed a resize bug, which uncovered a move bug which I also fixed.
Resize and moving seems to work pretty good.
There are some improvements I can imagine, like handling the point where you clicked for a move which would make it feel more snappy I guess.
And just while writing this I found more bugs.
The right most position for the last phrase was not calculated correctly and moving was broken if the content was not filling the widget.

**Comment by steveway** [comment]
Added the hotspot for moving the buttons. Feels indeed better and seems to work without added bugs.

**Comment by steveway** [comment]
Hi, did a few more small changes.
Also I experimented with Pyinstaller again.
The AboutDialog works if you copy the following files from PySide2 to the directory where you have the created .exe file:
- QtWebEngineProcess.exe
This folder is in the translations folder of PySide2:
- qtwebengine_locales
These files are in the resources folder of PySide2:
- icudtl.dat
- qtwebengine_devtools_resources.pak
- qtwebengine_resources.pak
- qtwebengine_resources_100p.pak
- qtwebengine_resources_200p.pak
It would be best if Pyinstaller includes these files correctly, but this would be a working workaround.

**Comment by steveway** [comment]
So, the mentioned problem with packaging is already solved for some time. There is a hook now available for PyInstaller.

Besides that I saw that work on QT6 has progressed quite a bit.
I've done some tests with PySide6 and this mostly works:
https://github.com/steveway/papagayo-ng/tree/qt6_test
The only real problems I found are that 2 QT parts we use are not yet supported by QT6.
QWebengine and QMultimedia.
To avoid the problem with QMultimedia I switched to the regular Soundplayer which just uses pydub and sounddevice.
And for QWebengine I changed the About Dialog to display everything using labels instead of a single HTML file.
That does actually work pretty well, including clicking on the links and feels better integrated.
Also we don't need a full web rendering engine to show the About Dialog this way:
![about_dialog_new](https://user-images.githubusercontent.com/3737094/124273237-0bf61a80-db40-11eb-85c2-0e0a059f3c67.png)
Looks quite good I think, at least not worse than the HTML version before.

**Comment by steveway** [comment]
So our dependency on QWebengine has been removed already.
Now to switch to QT6 we still kinda need QMultimedia.
Apparently this will now be back when QT6.2 is fully released:
https://www.qt.io/blog/qt-multimedia-in-qt-6
According to that Blog post QAudiodecoder will also be supported Cross Platform.
So we might be able to use SoundPlayerQT.py for all platforms if that works.

**Comment by steveway** [comment]
I added some styling possibilites.
In the settings you can now choose colors for all the elements of the Waveformview.
Also you can now set a .qss Stylesheet to change the appearance of the whole program.
![StyleSettings](https://user-images.githubusercontent.com/3737094/128524800-25f3d71a-3664-4400-9c77-1134c21c485b.png)
For example I tested this with a random dark theme I found here: https://qss-stock.devsecstudio.com/templates.php
And this is how that looks like, the theme/style is called "Obit".
![DarkThemeTest](https://user-images.githubusercontent.com/3737094/128525430-f080069b-e784-498a-9404-9c65a874d7ab.png)

As you can see this also changes the shape of our Waveform Objects, I turned the radius down a bit.
It's likely possible in the .qss file directly to exclude certain objects somehow.
Also the Icons and some text is difficult to read with this.
The text should be fixable inside the .qss file itself but icons need to be manually switched, so we need to add different icons.

**Comment by pabs3** [comment]
I noticed that the original Papagayo now has a new release that is already ported to Qt & C++ (instead of Python):

https://www.lostmarble.com/papagayo/
https://github.com/LostMoho/Papagayo

**Comment by marillat** [comment]
> I noticed that the original Papagayo now has a new release that is already ported to Qt & C++ (instead of Python):

Seems to be unmaintained. Last commit are from 2014.
